# Generated by Django 4.2.7 on 2023-11-22 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=255)),
                ('imagen_bandera', models.ImageField(upload_to='banderas/')),
                ('escudo_equipo', models.ImageField(upload_to='escudos/')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'Equipo',
                'db_table': 'Equipo',
                'ordering': ['nombre_equipo'],
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PosicionJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'Posicion',
                'db_table': 'Posicion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('rol', models.CharField(choices=[('Técnico', 'Técnico'), ('Asistente', 'Asistente'), ('Médico', 'Médico'), ('Preparador', 'Preparador')], max_length=255)),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundial.nacionalidad')),
            ],
            options={
                'verbose_name': 'coatch',
                'verbose_name_plural': 'Tecnico',
                'db_table': 'Tecnico',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('foto_jugador', models.ImageField(upload_to='fotos_jugadores/')),
                ('fecha_nacimiento', models.DateField()),
                ('posicion', models.CharField(max_length=255)),
                ('numero_camiseta', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundial.equipo')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'Jugador',
                'db_table': 'jugador',
                'ordering': ['nombre'],
            },
        ),
    ]
