# Generated by Django 4.2.7 on 2023-11-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['nombre_equipo'], 'verbose_name': 'team', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['nombre'], 'verbose_name': 'player', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='posicionjuego',
            options={'ordering': ['nombre'], 'verbose_name': 'position', 'verbose_name_plural': 'Posiciones'},
        ),
        migrations.AlterModelOptions(
            name='tecnico',
            options={'ordering': ['nombre'], 'verbose_name': 'coach', 'verbose_name_plural': 'Técnicos'},
        ),
    ]
