# Generated by Django 4.2.7 on 2023-11-23 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0002_alter_equipo_options_alter_jugador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundial.posicionjuego'),
        ),
    ]
