# Generated by Django 4.2.7 on 2023-11-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0003_alter_jugador_posicion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nacionalidad',
            options={'ordering': ['nombre'], 'verbose_name': 'national', 'verbose_name_plural': 'Nacionalidades'},
        ),
        migrations.AlterModelTable(
            name='nacionalidad',
            table='Nacionalidades',
        ),
    ]
