# Generated by Django 4.2.7 on 2023-11-23 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0004_alter_nacionalidad_options_alter_nacionalidad_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nacionalidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Nacionalidad', 'verbose_name_plural': 'Nacionalidades'},
        ),
        migrations.AlterModelTable(
            name='nacionalidad',
            table='Nacionalidad',
        ),
    ]
