# Generated by Django 4.2.7 on 2023-11-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0005_alter_nacionalidad_options_alter_nacionalidad_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nacionalidad',
            options={},
        ),
        migrations.AlterModelTable(
            name='nacionalidad',
            table=None,
        ),
    ]
