# Generated by Django 4.2.7 on 2023-11-25 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0006_alter_nacionalidad_options_alter_nacionalidad_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nacionalidad',
            options={'ordering': ['nombre'], 'verbose_name': 'NATIONALITY', 'verbose_name_plural': 'Nacionalidades'},
        ),
        migrations.AlterModelTable(
            name='nacionalidad',
            table='Nacionalidades',
        ),
    ]
